FROM mcr.microsoft.com/dotnet/core/sdk:3.1

WORKDIR /app

RUN mv /root/.dotnet /root/.nuget /
RUN mkdir /.local/ /.nuget/packages
RUN chown 1000 /.dotnet /.nuget /.nuget/packages /.local

ADD compile-function.sh .
RUN chmod u+x compile-function.sh
RUN chown 1000 compile-function.sh

RUN adduser slsuser --uid 1000
ENV EF_CORE_VERSION 3.1.4
RUN su slsuser -c "dotnet tool install -g dotnet-ef --version $EF_CORE_VERSION"
ENV PATH "$PATH:/home/slsuser/.dotnet/tools"